### ISSUE TITLE
Slate editor error from fields with array of type "block"

### ISSUE THREAD

**Issue by philiphand** [sanity-io/sanity-plugin-internationalized-array#39]
Error when using portable text (array of type block) fields

I am experiencing an error when editing formattable text within internationalized arrays. The studio runs and the fields appear without issues, but when editing the text I get the following error when attempting to edit the field:

> Uncaught error: Cannot resolve a Slate point from DOM point: [object Text]

This is how the field is set up:
```
export const internationalizedArrayConfig = {
    languages,
    fieldTypes: [
        'string',
        defineField({
            name: 'formattedText',
            type: 'array',
            of: [{type: 'block'}]
        })
    ],
}

const plugins = [
  internationalizedArray(internationalizedArrayConfig),
]

// Inside the schema
		defineField({
			name: "formattedTextField",
			title: "Weight example",
			type: "internationalizedArrayFormattedText",
		}),
```
I do not get any issues with string fields of the type internationalizedArrayString, so the problem seems related to the default portable text editor. Is portable text currently incompatible with this plugin?

![image](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/44257880/f5d9b9c1-97b7-4aaf-864b-34cce037d9a8)
![image](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/44257880/0234094c-b581-4f30-bc2c-1ff1b4aec112)

**Comment by philiphand** [comment]
Solved by updating to the newest version of the plugin.

**Comment by chiholiu10** [comment]
Do you have entire file of how this part of the code is implemented, still missing the entire context.
